const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={settings:null,users:[],selected:null,panel:"overview"};
async function api(path,options={}){const opts={credentials:"same-origin",headers:{},...options};if(opts.body&&typeof opts.body!=="string"){opts.headers["Content-Type"]="application/json";opts.body=JSON.stringify(opts.body)}const res=await fetch(`/api${path}`,opts);let payload={};try{payload=await res.json()}catch{}if(!res.ok||payload.success===false)throw new Error(payload.error||`请求失败 (${res.status})`);return payload.data}
function toast(text,error=false){const el=$("#toast");el.textContent=text;el.classList.toggle("error",error);el.classList.remove("hidden");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add("hidden"),3200)}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function fmtTime(v){if(!v)return"从未";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString("zh-CN",{hour12:false})}
async function boot(){try{const s=await api("/auth/status");if(s.authenticated)showApp();else showLogin()}catch(e){showLogin();$("#login-error").textContent=e.message}}
function showLogin(){$("#login-view").classList.remove("hidden");$("#app-view").classList.add("hidden")}
async function showApp(){$("#login-view").classList.add("hidden");$("#app-view").classList.remove("hidden");await loadPanel(state.panel)}
async function login(e){e.preventDefault();const error=$("#login-error");error.textContent="";try{await api("/auth/login",{method:"POST",body:{token:$("#login-token").value}});$("#login-token").value="";await showApp()}catch(err){error.textContent=err.message}}
async function logout(){try{await api("/auth/logout",{method:"POST"})}finally{showLogin()}}
function switchPanel(name){state.panel=name;$$('.panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${name}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));const titles={overview:"总览",users:"陪伴对象",settings:"关系与行为",diagnostics:"运行诊断"};$("#page-title").textContent=titles[name];closeMenu();loadPanel(name)}
async function loadPanel(name){try{if(name==="overview")await loadOverview();if(name==="users")await loadUsers();if(name==="settings")await loadSettings();if(name==="diagnostics")await loadDiagnostics()}catch(e){if(e.message==="未登录")showLogin();else toast(e.message,true)}}
async function loadOverview(){const d=await api("/overview");$("#runtime-dot").style.background=d.plugin_enabled?"#2d9b67":"#c7513b";const stats=[["陪伴对象",d.target_count,"已授权目标"],["连续记忆",d.memory_users,"已建立资料"],["互动记录",d.message_count,"累计消息"],["长期备注",d.note_count,"可靠记忆"]];$("#overview-stats").innerHTML=stats.map(x=>`<article class="stat"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join("");$("#overview-users").innerHTML=d.users.length?d.users.map(userRow).join(""):'<p class="empty">还没有用户资料</p>';const details=[["关系定位",d.relationship],["主动关怀",d.proactive_enabled?"已启用":"已关闭"],["当前免打扰",d.quiet_now?"是":"否"],["时区",d.timezone]];$("#behavior-summary").innerHTML=details.map(x=>`<div><dt>${esc(x[0])}</dt><dd>${esc(x[1])}</dd></div>`).join("")}
function userRow(u){return `<div class="user-row"><span class="avatar">${esc((u.nickname||u.user_id).slice(0,1))}</span><div class="user-copy"><strong>${esc(u.nickname||u.user_id)}</strong><span>${esc(u.mood||"暂无状态")}</span></div><span class="badge">${u.is_target?"陪伴中":"仅存档"}</span></div>`}
async function loadUsers(){state.users=await api("/users");renderDirectory();if(state.selected&&state.users.some(x=>x.user_id===state.selected))await selectUser(state.selected);else if(state.users.length)await selectUser(state.users[0].user_id);else $("#user-editor").innerHTML='<p class="empty">还没有用户资料。先在设置里添加陪伴目标。</p>'}
function renderDirectory(){$("#users-list").innerHTML=state.users.length?state.users.map(u=>`<button class="directory-button ${u.user_id===state.selected?"active":""}" data-user="${esc(u.user_id)}"><span class="avatar">${esc((u.nickname||u.user_id).slice(0,1))}</span><span class="user-copy"><strong>${esc(u.nickname||u.user_id)}</strong><span>${esc(u.user_id)}</span></span></button>`).join(""):'<p class="empty">暂无用户</p>';$$('[data-user]').forEach(b=>b.onclick=()=>selectUser(b.dataset.user))}
async function selectUser(id){state.selected=id;renderDirectory();const u=await api(`/users/${encodeURIComponent(id)}`);const notes=(u.notes||[]).map((n,i)=>`<div class="note-item"><span>${esc(n)}</span><button data-note-delete="${i}" title="删除备注">×</button></div>`).join("")||'<p class="muted">暂无长期备注</p>';const recent=(u.recent||[]).slice().reverse().map(x=>`<div class="recent-item"><time>${esc(fmtTime(x.time))}</time>${esc(x.text)}</div>`).join("")||'<p class="muted">暂无近期互动</p>';$("#user-editor").className="surface";$("#user-editor").innerHTML=`<div class="user-editor-inner"><div class="editor-title"><span class="avatar">${esc((u.nickname||u.user_id).slice(0,1))}</span><div><h4>${esc(u.nickname||u.user_id)}</h4><p>${esc(u.user_id)} · ${u.is_target?"陪伴目标":"历史资料"}</p></div><div class="editor-actions"><button id="summary-button" class="secondary">更新摘要</button><button id="proactive-button" class="primary" ${u.is_target?"":"disabled"}>主动测试</button></div></div><div class="editor-grid"><label>专属称呼<input id="user-nickname" value="${esc(u.nickname)}" maxlength="40"></label><label>当前内在状态<input id="user-mood" value="${esc(u.mood)}" maxlength="160"></label><label class="full">可靠用户摘要<textarea id="user-summary" rows="5">${esc(u.summary)}</textarea></label><div class="full"><div class="surface-head"><h4>长期备注</h4><span class="badge">${u.notes.length} 条</span></div><div class="notes-list">${notes}</div><div class="inline-add"><input id="new-note" placeholder="补充一条可靠、明确的长期备注"><button id="add-note" class="secondary">添加</button></div></div><div class="full"><div class="surface-head"><h4>近期互动</h4><span class="badge">${u.recent_count} 条</span></div><div class="recent-list">${recent}</div></div><div class="full"><button id="save-user" class="primary">保存用户资料</button></div></div></div>`;$("#save-user").onclick=saveUser;$("#summary-button").onclick=generateSummary;$("#proactive-button").onclick=proactiveTest;$("#add-note").onclick=addNote;$$('[data-note-delete]').forEach(b=>b.onclick=()=>deleteNote(Number(b.dataset.noteDelete)))}
async function saveUser(){await api(`/users/${encodeURIComponent(state.selected)}`,{method:"PUT",body:{nickname:$("#user-nickname").value,mood:$("#user-mood").value,summary:$("#user-summary").value}});toast("用户资料已保存");await loadUsers()}
async function addNote(){const input=$("#new-note");if(!input.value.trim())return;await api(`/users/${encodeURIComponent(state.selected)}/notes`,{method:"POST",body:{text:input.value}});toast("长期备注已添加");await selectUser(state.selected)}
async function deleteNote(index){await api(`/users/${encodeURIComponent(state.selected)}/notes/${index}`,{method:"DELETE"});toast("备注已删除");await selectUser(state.selected)}
async function generateSummary(){await api(`/users/${encodeURIComponent(state.selected)}/summary`,{method:"POST"});toast("已开始整理摘要，稍后刷新查看")}
async function proactiveTest(){const b=$("#proactive-button");b.disabled=true;try{const d=await api(`/users/${encodeURIComponent(state.selected)}/proactive-test`,{method:"POST"});toast(`主动测试完成，触发 ${d.sent||0} 条`)}finally{b.disabled=false}}
function setField(name,value){const el=$(`[name="${name}"]`);if(!el)return;if(el.type==="checkbox")el.checked=Boolean(value);else el.value=Array.isArray(value)?value.join(", "):(value??"")}
async function loadSettings(){state.settings=await api("/settings");Object.entries(state.settings).forEach(([section,values])=>Object.entries(values).forEach(([key,value])=>setField(`${section}.${key}`,value)))}
function val(name,type="text"){const el=$(`[name="${name}"]`);if(type==="bool")return el.checked;if(type==="int")return Number.parseInt(el.value,10);if(type==="float")return Number.parseFloat(el.value);if(type==="list")return el.value.split(/[,，\s]+/).map(x=>x.trim()).filter(Boolean);return el.value.trim()}
async function saveSettings(){const body={plugin:{enabled:val("plugin.enabled","bool"),target_mode:val("plugin.target_mode"),target_qqs:val("plugin.target_qqs","list"),admin_qqs:val("plugin.admin_qqs","list")},persona:{user_nickname:val("persona.user_nickname"),relationship:val("persona.relationship"),shared_background:val("persona.shared_background"),companion_style:val("persona.companion_style"),inject_in_groups:val("persona.inject_in_groups","bool")},proactive:{enabled:val("proactive.enabled","bool"),check_interval_minutes:val("proactive.check_interval_minutes","int"),min_silence_hours:val("proactive.min_silence_hours","float"),min_gap_hours:val("proactive.min_gap_hours","float"),max_per_day:val("proactive.max_per_day","int"),chance_percent:val("proactive.chance_percent","int"),quiet_start_hour:val("proactive.quiet_start_hour","int"),quiet_end_hour:val("proactive.quiet_end_hour","int"),timezone:val("proactive.timezone")},memory:{enabled:val("memory.enabled","bool"),recent_message_count:val("memory.recent_message_count","int"),max_notes:val("memory.max_notes","int"),auto_summary_every:val("memory.auto_summary_every","int"),llm_model_task:val("memory.llm_model_task")}};await api("/settings",{method:"PUT",body});toast("设置已保存并应用");await loadSettings()}
async function loadDiagnostics(){const d=await api("/diagnostics");const labels={plugin_version:"插件版本",webui_running:"面板服务",webui_uptime_seconds:"运行时长（秒）",scheduler_running:"主动调度器",summary_jobs:"摘要任务",indexed_sessions:"会话索引",state_file:"状态文件",state_bytes:"状态大小（字节）",config_file:"配置文件",target_mode:"目标模式",target_users:"当前目标用户",quiet_now:"当前免打扰"};$("#diagnostics-grid").innerHTML=Object.entries(d).map(([k,v])=>`<article class="diagnostic"><span>${esc(labels[k]||k)}</span><strong>${esc(Array.isArray(v)?v.join(", "):(typeof v==="boolean"?(v?"正常 / 是":"否"):v))}</strong></article>`).join("")}
function openMenu(){$(".sidebar").classList.add("open");$("#backdrop").classList.remove("hidden")}function closeMenu(){$(".sidebar").classList.remove("open");$("#backdrop").classList.add("hidden")}
$("#login-form").addEventListener("submit",login);$("#logout-button").onclick=logout;$("#save-settings").onclick=saveSettings;$("#menu-button").onclick=openMenu;$("#backdrop").onclick=closeMenu;$$('.nav-item').forEach(b=>b.onclick=()=>switchPanel(b.dataset.panel));$$('.refresh').forEach(b=>b.onclick=()=>loadPanel(state.panel));$$('[data-goto]').forEach(b=>b.onclick=()=>switchPanel(b.dataset.goto));setInterval(()=>{$("#clock").textContent=new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",hour12:false})},1000);boot();
